trigger:
  branches:
    include:
    - master

variables:
  - name: csproj
    value: 'MauiTestingUiMaestro/MauiTestingUiMaestro.csproj'
  - name: appVersionBuild
    value: 1
  - name: version
    value: $[format('{0:yyyy}.{0:MM}.{0:dd}.{0:HH}', pipeline.startTime)]
pool:
  vmImage: macos-13

jobs:
  - job:
    displayName: Generate Android Bundle/Apk
    steps:
    - template: Templates/build_release_android.yaml
      parameters:
        csproj: $(csproj)
        netVersion: 8.0.201
        appVersion: $(version)
        appVersionBuild: $(appVersionBuild)
        keyStoreFileName: testkeystore.jks
        keyStorePass: testkeystore
        keyStoreAlias: testkeystore
        keyStoreAliasPass: testkeystore