trigger:
  branches:
    include:
    - master

variables:
  - group: SecretAligner.Telemedicine.Mobile
  - name: csproj
    value: 'MauiTestingUiMaestro/MauiTestingUiMaestro.csproj'
  - name: appVersionBuild
    value: 1
  - name: version
    value: $[format('{0:yyyy}.{0:MM}.{0:dd}.{0:HH}', pipeline.startTime)]
pool:
  vmImage: macos-13

jobs:
  - job:
    displayName: Generate Android Bundle/Apk
    steps:
    - template: Templates/build_release_android.yaml
      parameters:
        csproj: $(csproj)
        netVersion: $(net-8-maui)
        appVersion: $(version)
        appVersionBuild: $(appVersionBuild)
        keyStoreFileName: $(android-keystore-file-name)
        keyStorePass: $(android-key-store-pass)
        keyStoreAlias: $(android-key-store-alias)
        keyStoreAliasPass: $(android-key-store-alias-pass)